server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1234
    url: idbc:postgresql://localhost:5432/registration
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        form_sql: true
    show-sql: true
